using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using System.Reflection;
using System.Xml.Linq;
using System;
using System.Collections.Generic;

namespace Foxy.Params.SourceGenerator
{
    partial class ParamsIncrementalGenerator : IIncrementalGenerator
    {
        private void GenerateSource(SourceProductionContext context, ImmutableArray<ParamsCandidate> typeSymbols)
        {
            foreach (var uniqueClass in typeSymbols
                .Where(e => !e.HasErrors)
                .GroupBy(e => e.TypeInfo))
            {
                var typeInfo = uniqueClass.Key;
                var sb = new SourceBuilder();
                sb.AutoGenerated();
                sb.AppendLine();
                sb.NullableEnable();
                sb.AppendLine();
                sb.Namespace(typeInfo.Namespace);
                sb.Class(typeInfo.TypeName);
                var maxOverridesMax = 0;
                foreach (var item in uniqueClass)
                {
                    var maxOverrides = 3;
                    var maxOverrideArg = item.AttributeSyntax.NamedArguments.FirstOrDefault(e => e.Key == "MaxOverrides");
                    if (maxOverrideArg.Key != null)
                    {
                        maxOverrides = (int)maxOverrideArg.Value.Value;
                    }
                    string name = item.MethodSymbol.Name;
                    var preArguments = GetNonParamsArguments(item.MethodSymbol);
                    var argName = "args";

                    for (int i = 1; i <= maxOverrides; i++)
                    {
                        if (i > 1)
                        {
                            sb.AppendLine();
                        }
                        sb.Method(name,
                            preArguments.Select(e => e.ToParameter()).Concat(Enumerable.Range(0, i).Select(j => $"object {argName}{j}")));
                        sb.AppendLine($"var foxyParamsArray = new Arguments{i}<object>({string.Join(", ", Enumerable.Range(0, i).Select(j => $"{argName}{j}"))});");
                        sb.AppendLine($"{name}({string.Join(", ", preArguments.Select(e => e.Name))}, global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref foxyParamsArray.arg0, {i}));");
                        sb.CloseBlock();
                    }

                    sb.AppendLine();
                    sb.Method(name, preArguments.Select(e => e.ToParameter()).Append($"params object[] {argName}"));
                    sb.AppendLine($"{name}({string.Join(", ", preArguments.Select(e => e.Name))}, new global::System.ReadOnlySpan<object>(args));");
                    sb.CloseBlock();
                    maxOverridesMax = Math.Max(maxOverridesMax, maxOverrides);
                }
                sb.CloseBlock();
                for (int i = 1; i <= maxOverridesMax; i++)
                {
                    sb.AppendLine();
                    CreateArguments(sb, i);
                }
                sb.CloseBlock();
                context.AddSource(uniqueClass.Key.CreateFileName(), SourceText.From(sb.ToString(), Encoding.UTF8));
            }

        }

        private static List<ArgumentInfo> GetNonParamsArguments(IMethodSymbol methodSymbol)
        {
            var parameters = new List<ArgumentInfo>();
            foreach (var arg in methodSymbol.Parameters.Take(methodSymbol.Parameters.Length - 1))
            {
                var type = arg.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var name = arg.Name;
                parameters.Add(new ArgumentInfo
                {
                    Name = name,
                    Type = type,
                });
            }
            return parameters;
        }

        private void CreateArguments(SourceBuilder sb, int length)
        {
            sb.Attribute($"System.Runtime.CompilerServices.InlineArray({length})");
            sb.GenericStruct($"Arguments{length}", "T");
            sb.Field("T", "arg0");
            sb.AppendLine();
            sb.Constructor(Enumerable.Range(0, length).Select(e => $"T value{e}"));
            sb.AppendLine($"arg0 = value0;");
            for (int i = 1; i < length; i++)
            {
                sb.AppendLine($"this[{i}] = value{i};");
            }
            sb.CloseBlock();
            sb.CloseBlock();
        }
    }

    public class ArgumentInfo
    {
        public string Type { get; set; }
        public string Name { get; set; }

        public string ToParameter()
        {
            return $"{Type} {Name}";
        }
    }
}

