// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        public static void Format<T, F, G, H>(string format, object args0)
            where T : struct
            where F : class, global::System.ICloneable, new()
            where G : notnull, global::System.Attribute
            where H : unmanaged
        {
            var foxyParamsArray = new Arguments1<object>(args0);
            Format<T, F, G, H>(format, global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref foxyParamsArray.arg0, 1));
        }

        public static void Format<T, F, G, H>(string format, params object[] args)
            where T : struct
            where F : class, global::System.ICloneable, new()
            where G : notnull, global::System.Attribute
            where H : unmanaged
        {
            Format<T, F, G, H>(format, new global::System.ReadOnlySpan<object>(args));
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;
        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }
}
