// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        public static T Format<T>(string format, object args0)
            where T : class, global::System.ICloneable, new()
        {
            var foxyParamsArray = new Arguments1<object>(args0);
            return Format<T>(format, global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref foxyParamsArray.arg0, 1));
        }

        public static T Format<T>(string format, params object[] args)
            where T : class, global::System.ICloneable, new()
        {
            return Format<T>(format, new global::System.ReadOnlySpan<object>(args));
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;

        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }
}
