# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  vitecommerce-ui:
    image: ${DOCKER_REGISTRY-}vitecommerce-ui
    container_name: vitecommerce-ui
    build:
      context: ./ViteCommerce.UI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  vitecommerce-api:
    image: ${DOCKER_REGISTRY-}vitecommerce-api
    container_name: vitecommerce-api
    build:
      context: .
      dockerfile: ViteCommerce.Api/Dockerfile
