# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  vitecommerce-api:
    image: ${DOCKER_REGISTRY-}vitecommerce-api
    container_name: vitecommerce-api
    build:
      context: .
      dockerfile: ViteCommerce.Api/Dockerfile
      target: build
    entrypoint: dotnet ViteCommerce.Api.dll

    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/app_database.db;

    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./container_data:/app/data:rw
