# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  vitecommerce-ui:
    image: ${DOCKER_REGISTRY-}vitecommerce-ui
    container_name: vitecommerce-ui
    build:
      context: ./ViteCommerce.UI
      dockerfile: Dockerfile
    entrypoint: node --inspect=0.0.0.0:9229 ./server/index.js

    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "9229:9229"

  vitecommerce-api:
    image: ${DOCKER_REGISTRY-}vitecommerce-api
    container_name: vitecommerce-api
    build:
      context: .
      dockerfile: ViteCommerce.Api/Dockerfile
      target: build
    entrypoint: dotnet ViteCommerce.Api.dll

    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages

    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
