// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        public static global::Something.Foo.InnerClass Format(global::Something.Foo.InnerClass format, global::Something.Foo.InnerClass args0)
        {
            var foxyParamsArray = new Arguments1<global::Something.Foo.InnerClass>(args0);
            return Format(format, global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref foxyParamsArray.arg0, 1));
        }

        public static global::Something.Foo.InnerClass Format(global::Something.Foo.InnerClass format, params global::Something.Foo.InnerClass[] args)
        {
            return Format(format, new global::System.ReadOnlySpan<global::Something.Foo.InnerClass>(args));
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;

        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }
}
