// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        public static void Format(string format, object args0)
        {
            var foxyParamsArray = new Arguments1<object>(args0);
            Format(format, global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref foxyParamsArray.arg0, 1));
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;
        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }
}
